# Generated by Django 5.1.4 on 2025-02-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pedido_options'),
    ]

    operations = [
    ]
